### ISSUE TITLE
Diagramm bei click groß bleiben

### ISSUE THREAD

**Issue by 96Sabiii** [96Sabiii/PSMG#5]
Der Schwappach meinte, dass er es gut fände, dass wenn man auf ein Diagramm click, der Zoom so bleibt. Also wie ein Pop-up. Das wenn man zB eine andere Seite aufmacht um was zu vergleichen das Diagramm weiterhin groß ist und nicht wieder klein wird, wenn man mit der Maus weg geht.
Hier wäre es dann wsl sinnvoll, wenn man ein X oben einbaut. das das Pop-up wieder schließt oder Ähnliches.

**Comment by MalAquita87** [comment]
https://www.w3schools.com/howto/howto_css_modals.asp  damit könnts funktionieren?!
