### ISSUE TITLE
Bubbles ausblenden

### ISSUE THREAD

**Issue by 96Sabiii** [96Sabiii/PSMG#7]
Wenn man bei den Zaubersprüchen auf einen Button klickt sollen die alten Bubbles erst langsam verschwinden bevor die neuen eingeblendet werden.

**Comment by 96Sabiii** [comment]
blenden aus, aber buggt bei vielen versuchen beim wieder einblenden..

**Comment by MalAquita87** [comment]
Duration n bissi verringert- bei mir nach vielen, vielen Tests kein bug, funktioniert einwandfrei.
